### ISSUE TITLE
Usage of the code and models

### ISSUE THREAD

**Issue by TejaswiniiB** [sangHa0411/CloneDetection#12]
Thanks for clone detection repo for Python language.

1. Are there are any datasets available for clone detection task (10 million python code pairs)?
2. Are there any trained models to replicate the results presented in the pdf?

**Comment by snoop2head** [comment]
**Dataset per fold are following:**
- https://huggingface.co/datasets/PoolC/1-fold-clone-detection-600k-5fold
- https://huggingface.co/datasets/PoolC/2-fold-clone-detection-600k-5fold
- https://huggingface.co/datasets/PoolC/3-fold-clone-detection-600k-5fold
- https://huggingface.co/datasets/PoolC/4-fold-clone-detection-600k-5fold
- https://huggingface.co/datasets/PoolC/5-fold-clone-detection-600k-5fold

Those pairs are combination based on [Dacon's 45000 codes](https://dacon.io/competitions/official/235900/data).

Trained models are currently unavailable, but if you notify us the purpose of clone detection, 
we will support you to run the repository's code!

**Comment by sangHa0411** [comment]
> Thanks for clone detection repo for Python language.
> 
> 1. Are there are any datasets available for clone detection task (10 million python code pairs)?
> 2. Are there any trained models to replicate the results presented in the pdf?

Hi. Thanks for your question

1. You can download codes from this link : https://dacon.io/competitions/official/235900/overview/description. This dataset has total 300 problems and each problem has 150 codes. Out team made 10 million python code pair from just this dataset.

**Comment by TejaswiniiB** [comment]
Thankyou for the quick response @sangHa0411 @snoop2head 
I will try to understand and use the code in this repository. Will get back to you if need any support is needed.
